before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: 
      - -s -w -X main.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc

